// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfPXkfCfFtgX4sbPiqvO-9Hx4CAZbQOT4',
    appId: '1:995782258015:web:cee4f5202b635935d0daea',
    messagingSenderId: '995782258015',
    projectId: 'intern-database-48a8c',
    authDomain: 'intern-database-48a8c.firebaseapp.com',
    storageBucket: 'intern-database-48a8c.firebasestorage.app',
    measurementId: 'G-NVMD4NFL1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBtD3ZoHiwxLAI-ZdqgvqEfM7oG0RvDEI',
    appId: '1:995782258015:android:ab943ffe3e39a3d2d0daea',
    messagingSenderId: '995782258015',
    projectId: 'intern-database-48a8c',
    storageBucket: 'intern-database-48a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPA7ONgalMoi8dh1diSZzyWRmLiwsqUX8',
    appId: '1:995782258015:ios:4c004b271a2a1fe8d0daea',
    messagingSenderId: '995782258015',
    projectId: 'intern-database-48a8c',
    storageBucket: 'intern-database-48a8c.firebasestorage.app',
    iosBundleId: 'com.example.internWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPA7ONgalMoi8dh1diSZzyWRmLiwsqUX8',
    appId: '1:995782258015:ios:4c004b271a2a1fe8d0daea',
    messagingSenderId: '995782258015',
    projectId: 'intern-database-48a8c',
    storageBucket: 'intern-database-48a8c.firebasestorage.app',
    iosBundleId: 'com.example.internWork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfPXkfCfFtgX4sbPiqvO-9Hx4CAZbQOT4',
    appId: '1:995782258015:web:976c126355c31235d0daea',
    messagingSenderId: '995782258015',
    projectId: 'intern-database-48a8c',
    authDomain: 'intern-database-48a8c.firebaseapp.com',
    storageBucket: 'intern-database-48a8c.firebasestorage.app',
    measurementId: 'G-S2GJX2N79F',
  );

}